### ISSUE TITLE
Infinite loop when iterating through a job output

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#105]
**Describe the bug**
When iterating through a `job`'s `output`, an infinite loop is created. Is this the expected behavior? I can kind of see why this may be the case, but I'm not 100% confident.

```python
# this is in test_modules.py
from dataclasses import dataclass

from jobflow import Flow, Maker, job


@dataclass
class Adder(Maker):
    name: str = "Adder"

    @job
    def make(self, num1, num2):
        return num1 + num2


@dataclass
class test(Maker):
    name: str = "test"
    adder_maker1: Maker = Adder()
    adder_maker2: Maker = Adder()

    def make(self, num1, num2):
        job1 = self.adder_maker1.make(num1, num2)
        job2 = self.adder_maker2.make(job1.output, num2)
        
        # this for loop causes an infinite loop -- why?
        for out in job1.output:
            print("test")

        return Flow([job1, job2])

```

The following is used to run the above code: 
```python
from test_modules import test
from jobflow.managers.local import run_locally

flow = test().make(1, 2)
out = run_locally(flow, ensure_success=True)
```

**Comment by utf** [comment]
Hmm, you're trying to loop over the output of a job that hasn't yet run. So on this line
```python
for out in job1.output:
```
job1.output is an `OutputReference` object.

I haven't defined the `__iter__` function for `OutputReference` so I'm not sure exactly what's happening here. I'll double check.

Either way, I'm not entirely sure what you expect the code to do at this point (other than give an error), as the output reference isn't be iterable.

**Comment by utf** [comment]
It turns out this behaviour is because I've implemented `OutputReference.__getitem__` which automatically makes an object iterable. In this case, as you iterate over the object it will return output references with increasing indices of the output as if the output was a list. But because jobflow doesn't know how many items are in the list (or even whether the output is a list at all) it will keep iterating till infinity.

I will fix by adding an `__iter__` function which raises an error.

For your code, remember, that in the make method for Flows, the job outputs have not yet been computed, so you can't iterate over them/perform mathematical operations, etc in the make method itself. If you need to do anything with the output of a job you need to do it in another job, as that way the outputs will get resolved before the job runs.

**Comment by arosen93** [comment]
Thanks for the detailed reply! I think in this case, what I would have expected that an error be thrown, so I like your solution to it. Every now and then, I've had a situation where the `.output` was a `List[Structure]` or something similar, and iterating through the `.output` would cause things to hang. Throwing an error would make it clearer that something is clearly wrong (and that I should be passing around the `.output` rather than doing anything with it, other than indexing it directly).

Since I was expecting an error, I was mostly confused about what the loop was _actually_ doing. Now I see!

**Comment by utf** [comment]
This should be fixed now :)
