### ISSUE TITLE
Configurable job_dir names?

### ISSUE THREAD

**Issue by janosh** [materialsproject/jobflow#128]
In the old `atomate` I liked the ability to shorten the names of job dirs via

```yaml
# FW_config.yaml
FW_BLOCK_FORMAT: "%Y-%m-%d@%H-%M"
```

The job dirs are currently created by:

```py
def _get_job_dir():
    if create_folders:
        time_now = datetime.utcnow().strftime("%Y-%m-%d-%H-%M-%S-%f")
        job_dir = root_dir / f"job_{time_now}-{randint(10000, 99999)}"
        job_dir.mkdir()
        return job_dir
    else:
        return root_dir
```

I'm curious what the random int is for and if we could make `time_now` configurable? Something like:

```py
# new kwarg template with default val None
if isinstance(template, str):
    now = f"{datetime.utcnow():{template}}"
elif callable(template):
    now = template()  # maybe pass in root_dir as arg? not sure if there's a use case for it
else:
    now = f"{datetime.utcnow():{%Y-%m-%d-%H-%M-%S-%f}}"
job_dir = root_dir / f"job_{now}-{randint(10000, 99999)}"
```

**Comment by utf** [comment]
I transferred the issue here. Definitely makes more sense. So a couple of points:

1. If you use fireworks to run jobflow workflows then you can use the usual fireworks methods for changing the folder names.
2. The random int is just in case you have two jobs that start at exactly the same time.
3. I'd be happy to have a customisable way to change the folder names. I think your suggestion would work well. But the default job name template should be defined in the jobflow settings file.

**Comment by utf** [comment]
I added a quick solution: There is now a `DIRECTORY_FORMAT` option in JobflowSettings which accepts a datatime format string. If you need even more control then I'd be happy to accept a PR :)

**Comment by janosh** [comment]
@utf Thanks! 👍  Yeah I think `datetime` formatting covers all but the rarest use cases.
