### ISSUE TITLE
BUG: `jsanitize` should not use `strict=True` when storing job output

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#149]
**Describe the bug**
When Jobflow tries to store the outputs of a `job`, it runs `jsanitize(response.output, strict=True, enum_values=True`). In my opinion, `strict` should not be set to `True` because this prevents the conversion of "unknown" object types to `str` and instead leads to a crash. For instance, consider the following imaginary numpy array:
```
test =  np.array([1 + 2j, 3 + 4j, 5 + 6j])
```
If this is in the output, `jsanitize` will lead to an error like that shown below rather than simply converting the unknown data types to a string.

A better solution is to instead use `jsanitize(response.output, enum_values=True, recursive_msonable=True)`, which will still call `.as_dict()` for MSONables but not on unknown data types. I added this kwarg a little while ago to `monty`. See additional context [here](https://github.com/materialsvirtuallab/monty/issues/343).

```python
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/jobflow/core/job.py", line 571, in run
    output = jsanitize(response.output, strict=True, enum_values=True)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/monty/json.py", line 505, in jsanitize
    return {
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/monty/json.py", line 506, in <dictcomp>
    k.__str__(): jsanitize(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/monty/json.py", line 499, in jsanitize
    return [jsanitize(i, strict=strict, allow_bson=allow_bson, enum_values=enum_values) for i in obj.tolist()]
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/monty/json.py", line 499, in <listcomp>
    return [jsanitize(i, strict=strict, allow_bson=allow_bson, enum_values=enum_values) for i in obj.tolist()]
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/monty/json.py", line 545, in jsanitize
    obj.as_dict(),
AttributeError: 'complex' object has no attribute 'as_dict'
```

**Comment by utf** [comment]
I think of `strict=True` as a feature not a bug. If the output is not valid json then it won't be stored in the database properly and can't be used by other jobs properly.

By enforcing strict, this will catch errors when they occur (when trying to store an invalid type) rather than downstream, e.g., when a job expects a list but gets a string instead. The former error is easy to catch and raise an understandable error message whereas the latter error will be confusing to track down. For example, users might confused why do I have a string of a numpy array instead of a list.

For that reason, I think its much better to catch malformed outputs rather than propagate them.

For the example you raised, the best solution is to add support for complex numpy arrays in monty itself. That is what I've done for dataclasses, pydantic models, UUIDs etc.

**Comment by arosen93** [comment]
Thanks for the detailed reply. I think your decision makes sense.

In the example I gave, I think that the data would still be stored as a list, but each entry in the list would be a str representation rather than a complex datatype. Still, I understand that creating lists (or dicts) of arbitrary datatypes is perhaps not the goal of Jobflow and should be sorted out by the developer in advance.

**Comment by utf** [comment]
Ah, yes, I see what you mean about the complex example. But ultimately it will still result in obscure error messages.

Thanks for raising this issue though. It was good to think about the practical impact of using strict!
